name: GitHubMonitor
options:
  bundleIdPrefix: com.githubmonitor
  deploymentTarget:
    macOS: "14.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.githubmonitor.app
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: "-"
    DEVELOPMENT_TEAM: ""
    SWIFT_VERSION: "6.0"

targets:
  GitHubMonitor:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources/GitHubMonitor
      - path: Assets.xcassets
    settings:
      base:
        PRODUCT_NAME: GitHub Monitor
        INFOPLIST_FILE: Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_HARDENED_RUNTIME: YES
        OTHER_SWIFT_FLAGS: "-DAPP_BUNDLE"
    info:
      path: Info.plist
      properties:
        CFBundleName: GitHub Monitor
        CFBundleDisplayName: GitHub Monitor
        CFBundleIdentifier: com.githubmonitor.app
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        NSPrincipalClass: NSApplication
        NSMainStoryboardFile: ""
        NSHighResolutionCapable: true
